SELECT
P.POLICY_TYPE,
COUNT(DISTINCT P.POLICY_ID) AS TOTAL_POLICIES,
COUNT(C.CLAIM_ID) AS TOTAL_CLAIMS,
ROUND(COUNT(C.CLAIM_ID) / COUNT(DISTINCT P.POLICY_ID), 2) AS CLAIM_TO_POLICY_RATIO
FROM POLICIES_INSURANCE P
LEFT JOIN CLAIM_INSURANCE C ON P.POLICY_ID = C.POLICY_ID
GROUP BY P.POLICY_TYPE
ORDER BY CLAIM_TO_POLICY_RATIO DESC;
