SELECT 
    C.CUSTOMER_ID,
    C.FULL_NAME,
    ROUND(AVG(PAY.AMOUNT), 2) AS AVG_PAYMENT_PER_CUSTOMER
FROM CUSTOMER_INSURANCE C
JOIN POLICIES_INSURANCE P 
    ON C.CUSTOMER_ID = P.CUSTOMER_ID
JOIN PAYMENTS_INSURANCE PAY 
    ON P.POLICY_ID = PAY.POLICY_ID
GROUP BY C.CUSTOMER_ID, C.FULL_NAME
ORDER BY AVG_PAYMENT_PER_CUSTOMER DESC; 