SELECT  
EXTRACT(YEAR FROM P.START_DATE) AS YEAR, 
SUM(P.PREMIUM_AMOUNT) AS TOTAL_PREMIUM,
NVL(SUM(C.CLAIM_AMOUNT), 0) AS TOTAL_CLAIM,
(SUM(P.PREMIUM_AMOUNT) - NVL(SUM(C.CLAIM_AMOUNT), 0)) AS NET_INCOME
FROM POLICIES_INSURANCE P
LEFT JOIN CLAIM_INSURANCE C
ON P.POLICY_ID = C.POLICY_ID
GROUP BY  EXTRACT(YEAR FROM P.START_DATE)
ORDER BY YEAR;
