SELECT 
P.AGENT_ID,
SUM(P.PREMIUM_AMOUNT) AS TOTAL_PREMIUM_AMOUNT,
SUM(C.CLAIM_AMOUNT) AS TOTAL_CLAIM_AMOUNT
FROM POLICIES_INSURANCE P
LEFT JOIN CLAIM_INSURANCE C
ON P.POLICY_ID = C.POLICY_ID
GROUP BY P.AGENT_ID
ORDER BY P.AGENT_ID; 
