SELECT C.CITY, COUNT(C.CUSTOMER_ID) AS COUNT_OF_CUSTOMERS, 
ROUND(AVG(P.PREMIUM_AMOUNT), 0) AS AVG_PREMIUM_AMOUNT
FROM CUSTOMER_INSURANCE C
INNER JOIN POLICIES_INSURANCE P
ON C.CUSTOMER_ID = P.CUSTOMER_ID
GROUP BY C.CITY;