SELECT 
   C.CUSTOMER_ID,
   C.FULL_NAME,
   SUM(P.PREMIUM_AMOUNT) AS TOTAL_PREMIUM,
   SUM(CL.CLAIM_AMOUNT) AS TOTAL_CLAIM,
   ROUND((NVL(SUM(CL.CLAIM_AMOUNT), 0) / NULLIF(SUM(P.PREMIUM_AMOUNT), 0)) * 100, 2) AS CLAIM_RATIO_PERCENT
FROM CUSTOMER_INSURANCE C
JOIN POLICIES_INSURANCE P 
   ON C.CUSTOMER_ID = P.CUSTOMER_ID
LEFT JOIN CLAIM_INSURANCE CL 
   ON P.POLICY_ID = CL.POLICY_ID
GROUP BY C.CUSTOMER_ID, C.FULL_NAME
ORDER BY CLAIM_RATIO_PERCENT DESC;