SELECT A.BRANCH, SUM(PA.AMOUNT) AS TOTAL_AMOUNT
FROM POLICIES_INSURANCE P
INNER JOIN PAYMENTS_INSURANCE PA
ON PA.POLICY_ID = P.POLICY_ID
INNER JOIN AGENTS_INSURANCE A
ON P.AGENT_ID = A.AGENT_ID
GROUP BY A.BRANCH
ORDER BY TOTAL_AMOUNT DESC
FETCH FIRST 3 ROWS ONLY;
