SELECT 
ROUND(
    (COUNT(CASE WHEN P.START_DATE < PAY.PAYMENT_DATE THEN 1 END) * 100.0) 
    / COUNT(*), 2
) AS DELAYED_PAYMENT_PERCENT
FROM POLICIES_INSURANCE P
JOIN PAYMENTS_INSURANCE PAY ON P.POLICY_ID = PAY.POLICY_ID;  