SELECT 
A.REGION,
ROUND(
    (SUM(P.PREMIUM_AMOUNT) - COALESCE(SUM(C.CLAIM_AMOUNT), 0)) 
    / SUM(P.PREMIUM_AMOUNT) * 100, 2
) AS PROFITABILITY_PERCENT
FROM POLICIES_INSURANCE P
JOIN AGENTS_INSURANCE A ON P.AGENT_ID = A.AGENT_ID
LEFT JOIN CLAIM_INSURANCE C ON P.POLICY_ID = C.POLICY_ID
GROUP BY A.REGION
ORDER BY A.REGION;
