SELECT 
    A.AGENT_ID,
    A.AGENT_NAME,
    SUM(P.PREMIUM_AMOUNT) AS TOTAL_PREMIUM,
    SUM(C.CLAIM_AMOUNT) AS TOTAL_CLAIM,
    ROUND(
        ((SUM(P.PREMIUM_AMOUNT) - SUM(C.CLAIM_AMOUNT)) / SUM(P.PREMIUM_AMOUNT)) * 100, 
    2) AS PROFITABILITY_PERCENT
FROM AGENTS_INSURANCE A
JOIN POLICIES_INSURANCE P 
    ON A.AGENT_ID = P.AGENT_ID
LEFT JOIN CLAIM_INSURANCE C 
    ON P.POLICY_ID = C.POLICY_ID
GROUP BY 
    A.AGENT_ID, 
    A.AGENT_NAME
ORDER BY 
    PROFITABILITY_PERCENT DESC;
