SELECT 
PAYMENT_METHOD,
COUNT(*) AS PAYMENT_COUNT,
ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM PAYMENTS_INSURANCE), 2) AS PERCENTAGE_SHARE
FROM PAYMENTS_INSURANCE
GROUP BY PAYMENT_METHOD
ORDER BY PAYMENT_COUNT DESC;
